#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Answer.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Answer_cshtml_ : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.AnswerViewModel>
    {
        public _Views_Shared_DisplayTemplates_Answer_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
  
    var canVote = ViewBag.CanVote != false;
    var canFlag = !Model.IHaveFlagged;
    
    var voteClass = Model.HasMyVote ? "is-active" : String.Empty;
    
    var flaggedClass = Model.IHaveFlagged ? "is-active" : String.Empty;

    var votesText = Model.VoteCount == 1 ? "Vote" : "Votes";

    var disabled = "disabled=disabled";

    var isMyQuestion = (bool?)ViewBag.IsMyQuestion == true;
    
    var cardClass = string.Empty;
    
    if (Model.IsMyAnswer)
    {
        cardClass += " is-mine";
    }

    if (Model.IsStarVote)
    {
        cardClass += " is-star";
    }

    if (Model.IsPopularVote)
    {
        cardClass += " is-upvoted";
    }
        

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"Answers\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 793), Tuple.Create("\"", 851)
, Tuple.Create(Tuple.Create("", 801), Tuple.Create("Card", 801), true)
, Tuple.Create(Tuple.Create(" ", 805), Tuple.Create("Answer", 806), true)
            
            #line 37 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
, Tuple.Create(Tuple.Create(" ", 812), Tuple.Create<System.Object, System.Int32>(cardClass
            
            #line default
            #line hidden
, 813), false)
, Tuple.Create(Tuple.Create(" ", 823), Tuple.Create("user-level-", 824), true)
            
            #line 37 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
, Tuple.Create(Tuple.Create("", 835), Tuple.Create<System.Object, System.Int32>(Model.UserLevel
            
            #line default
            #line hidden
, 835), false)
);

WriteLiteral(">\r\n        \r\n");

            
            #line 39 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
         if (Model.IsStarVote && Model.IsPopularVote && Model.IsMyAnswer)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n                Your answer + Most votes + Questioners Choice\r\n            </d" +
"iv>\r\n");

            
            #line 44 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        }
        else if (Model.IsStarVote && Model.IsPopularVote)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n                Most votes + Questioners Choice\r\n            </div>\r\n");

            
            #line 50 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        }
        else if (Model.IsStarVote && Model.IsMyAnswer)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n                Your answer + Questioners Choice\r\n            </div>\r\n");

            
            #line 56 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        }
        else if (Model.IsPopularVote && Model.IsMyAnswer)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n                Your answer + Most votes\r\n            </div>\r\n");

            
            #line 62 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        }
        else if (Model.IsStarVote)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-icon=\"star\"");

WriteLiteral("></span>\r\n                Best Answer as voted by the Questioner\r\n            </d" +
"iv>\r\n");

            
            #line 69 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        }
        else if (Model.IsPopularVote)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-icon=\"vote\"");

WriteLiteral("></span>\r\n                Most popular answer\r\n            </div>\r\n");

            
            #line 76 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        }
        else if (Model.IsMyAnswer)
        { 

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/Content/images/icons/user.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"20\"");

WriteLiteral(">\r\n                Your answer\r\n            </div>\r\n");

            
            #line 83 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    \r\n        <div");

WriteLiteral(" class=\"Dilemma-question Card-section\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Answer-text\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" style=\"white-space: pre-wrap\"");

WriteLiteral(">");

            
            #line 87 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                                            Write(Model.Text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div><!-- Dilemma-text -->\r\n");

            
            #line 89 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
            
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
             if (!Model.IsApproved && Model.IsMyAnswer)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" style=\"margin-top: 15px; color: #999; font-style: italic; font-size: 0.8em\"");

WriteLiteral(">\r\n");

            
            #line 92 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                     if (Model.IsRejected)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("This answer didn\'t pass moderation. Check you notifications to find out why. Reme" +
"mber to always follow the guidelines and be respectful!");

WriteLiteral("\r\n");

            
            #line 95 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("You\'re the only one who can see this answer until its been approved by a moderato" +
"r.");

WriteLiteral("\r\n");

            
            #line 99 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");

            
            #line 101 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div><!-- Dilemma-question Card-section -->\r\n\r\n        <div");

WriteLiteral(" class=\"Dilemma-actions Card-section line\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"u-2of5\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteAttribute("class", Tuple.Create(" class=\"", 3428), Tuple.Create("\"", 3514)
, Tuple.Create(Tuple.Create("", 3436), Tuple.Create("Button--vote", 3436), true)
            
            #line 106 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
, Tuple.Create(Tuple.Create(" ", 3448), Tuple.Create<System.Object, System.Int32>(Model.HasMyVote ? string.Empty : "js-voting-button"
            
            #line default
            #line hidden
, 3449), false)
            
            #line 106 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                                , Tuple.Create(Tuple.Create(" ", 3503), Tuple.Create<System.Object, System.Int32>(voteClass
            
            #line default
            #line hidden
, 3504), false)
);

WriteLiteral(" ");

            
            #line 106 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                                                                                                                         Write(canVote || Model.HasMyVote ? String.Empty : disabled);

            
            #line default
            #line hidden
WriteLiteral(" data-answer-id=\"");

            
            #line 106 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                                                                                                                                                                                                Write(Model.AnswerId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

            
            #line 107 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                     if (isMyQuestion)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"Button-label is-inactive\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" data-icon=\"star\"");

WriteLiteral("></span>\r\n                            Best <span");

WriteLiteral(" class=\"size-m-and-up inline\"");

WriteLiteral("> Answer</span>\r\n                        </span>\r\n");

WriteLiteral("                        <span");

WriteLiteral(" class=\"Button-label is-active\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" data-icon=\"star-active\"");

WriteLiteral("></span>\r\n                            Your Best <span");

WriteLiteral(" class=\"size-m-and-up inline\"");

WriteLiteral("> Answer</span>\r\n                        </span>\r\n");

            
            #line 117 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" data-icon=\"vote\"");

WriteLiteral("></span>\r\n");

WriteLiteral("                        <span");

WriteLiteral(" class=\"Button-label is-inactive\"");

WriteLiteral(">Vote</span>\r\n");

WriteLiteral("                        <span");

WriteLiteral(" class=\"Button-label is-active\"");

WriteLiteral(">Voted</span>\r\n");

            
            #line 123 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </button>                \r\n            </div>\r\n            <div");

WriteLiteral(" class=\"u-2of5\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"number-bubble\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"number-bubble--number\"");

WriteLiteral(">");

            
            #line 128 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                                                   Write(Model.VoteCount);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    <span");

WriteLiteral(" class=\"inline Card-label--small\"");

WriteLiteral(">");

            
            #line 129 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                                                      Write(votesText);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n                  \r\n            </div>\r\n        " +
"    <div");

WriteLiteral(" class=\"u-1of5 right\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteAttribute("class", Tuple.Create(" class=\"", 4908), Tuple.Create("\"", 4957)
, Tuple.Create(Tuple.Create("", 4916), Tuple.Create("Button--flag", 4916), true)
, Tuple.Create(Tuple.Create(" ", 4928), Tuple.Create("js-flag-button", 4929), true)
            
            #line 134 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
, Tuple.Create(Tuple.Create(" ", 4943), Tuple.Create<System.Object, System.Int32>(flaggedClass
            
            #line default
            #line hidden
, 4944), false)
);

WriteLiteral(" title=\"Report an issue with this answer\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#modal-flag\"");

WriteLiteral(" ");

            
            #line 134 "..\..\Views\Shared\DisplayTemplates\Answer.cshtml"
                                                                                                                                                                           Write(canFlag ? String.Empty : disabled);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"flag\"");

WriteLiteral("></span> \r\n                    <span");

WriteLiteral(" class=\"Button-label is-inactive\"");

WriteLiteral(">Flag</span>\r\n                    <span");

WriteLiteral(" class=\"Button-label is-active\"");

WriteLiteral(">Flagged</span>\r\n                </button>                 \r\n            </div>\r\n" +
"        </div><!-- Dilemma-actions -->\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
