#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/ModerationEntry.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_ModerationEntry_cshtml_ : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.ModerationEntryViewModel>
    {
        public _Views_Shared_DisplayTemplates_ModerationEntry_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<article");

WriteLiteral(" class=\"Dilemma Card\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"Card-section Card-info\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"line align-center\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Card-label--small\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 7 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
           Write(Model.CreatedDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" style=\"margin-bottom: 20px\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n    \r\n    <div");

WriteLiteral(" class=\"Card-section\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"Dilemma-question\"");

WriteLiteral(">\r\n            \r\n");

            
            #line 16 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
             switch (Model.State)
            {
                case ModerationState.Queued:
                case ModerationState.ReQueued:
                    

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"Moderation-entry-text \"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Added to Moderation Queue</div>\r\n                    </div>\r\n");

            
            #line 24 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
            
                    break;
                case ModerationState.Approved:
                    

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"Moderation-entry-text \"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Approved by Moderator</div>\r\n                    </div>\r\n");

            
            #line 31 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
            
                    break;
                case ModerationState.Rejected:
                

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"Moderation-entry-text \"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"font-weight: bold; margin-bottom: 10px\"");

WriteLiteral(">Rejected by Moderator</div>\r\n                        <div");

WriteLiteral(" style=\"font-style: italic; margin: 0 50px; color: #888\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" style=\"white-space: pre-wrap\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
                                                        Write(HttpUtility.HtmlDecode(Model.Message));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 41 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
            
                    break;
                    
                case ModerationState.Reported:
                    

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"Moderation-entry-text \"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"font-weight: bold; margin-bottom: 10px\"");

WriteLiteral(">Reported by another User</div>\r\n                        <div");

WriteLiteral(" style=\"font-style: italic; margin: 0 50px; color: #888\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" style=\"white-space: pre-wrap\"");

WriteLiteral(">");

            
            #line 49 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
                                                        Write(HttpUtility.HtmlDecode(Model.Message));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 52 "..\..\Views\Shared\DisplayTemplates\ModerationEntry.cshtml"
            
                    break;
                    
                default:
                    throw new ArgumentOutOfRangeException();
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div> \r\n    </div>\r\n</article>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
