#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Notifications.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Notifications_cshtml_ : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.NotificationListViewModel>
    {
        public _Views_Shared_DisplayTemplates_Notifications_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"Card Notification Card-go--container\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"Card-go--trigger\"");

WriteLiteral("></a>\r\n    <div");

WriteLiteral(" class=\"Notification-score\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
         if (Model.TotalPointsAwarded == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n                <span");

WriteLiteral(" data-icon=\"notification\"");

WriteLiteral("></span>\r\n            </div>\r\n");

            
            #line 11 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
            Write(string.Format("{0}{1}", Model.TotalPointsAwarded > 0 ? "+" : string.Empty, Model.TotalPointsAwarded));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" class=\"Notification-score-label\"");

WriteLiteral(">Points</span>\r\n            </div>\r\n");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <div");

WriteLiteral(" class=\"Notification-summary\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"Card-label--small\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
                                  Write(Model.CreatedDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"Notification-summary-text\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
             switch (Model.NotificationType)
            {
                case NotificationType.QuestionAnswered:

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("You have new advice for your dilemma!");

WriteLiteral("\r\n");

            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
                    break;
                case NotificationType.PostRejected:

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("One of your posts has been rejected by a moderator. Find out why.");

WriteLiteral("\r\n");

            
            #line 29 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
                    break;
                case NotificationType.PointsAwarded:

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("POINTS AWARDED");

WriteLiteral("\r\n");

            
            #line 32 "..\..\Views\Shared\DisplayTemplates\Notifications.cshtml"
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div><!-- Notification-summary -->\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
