#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    
    #line 1 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
    using Dilemma.Web.Extensions;
    
    #line default
    #line hidden
    using Disposable.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/QuestionListViewModel.cshtml")]
    public partial class QuestionListViewModel_ : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.QuestionListViewModel>
    {
        public QuestionListViewModel_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>Question</th>\r\n        <th");

WriteLiteral(" style=\"min-width: 110px\"");

WriteLiteral(">Created</th>\r\n        <th");

WriteLiteral(" style=\"min-width: 110px\"");

WriteLiteral(">Closes</th>\r\n        <th>Answers</th>\r\n        <th>Category</th>\r\n        <th></" +
"th>\r\n    </tr>\r\n\r\n");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
 foreach (var item in Model.Questions)
{
    var answerPercentage = Convert.ToInt32(item.TotalAnswers * 100 / item.MaxAnswers);
    var rowClass = item.IsMyQuestion ? "bg-info" : string.Empty;
    

            
            #line default
            #line hidden
WriteLiteral("    <tr");

WriteAttribute("class", Tuple.Create(" class=\"", 547), Tuple.Create("\"", 564)
            
            #line 19 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 555), Tuple.Create<System.Object, System.Int32>(rowClass
            
            #line default
            #line hidden
, 555), false)
);

WriteLiteral(">\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(Html.DisplayFor(modelItem => item.Text));

            
            #line default
            #line hidden
WriteLiteral(" \r\n        </td>\r\n        <td>\r\n            <div");

WriteAttribute("title", Tuple.Create(" title=\"", 682), Tuple.Create("\"", 711)
            
            #line 24 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 690), Tuple.Create<System.Object, System.Int32>(item.CreatedDateTime
            
            #line default
            #line hidden
, 690), false)
);

WriteLiteral(">");

            
            #line 24 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                          Write(item.CreatedDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </td>\r\n        <td>\r\n            <div");

WriteAttribute("title", Tuple.Create(" title=\"", 804), Tuple.Create("\"", 832)
            
            #line 27 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 812), Tuple.Create<System.Object, System.Int32>(item.ClosesDateTime
            
            #line default
            #line hidden
, 812), false)
);

WriteLiteral(">");

            
            #line 27 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                         Write(item.ClosesDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </td>\r\n        <td>\r\n            <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(" style=\"margin-bottom: 5px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"progress-bar\"");

WriteLiteral(" role=\"progressbar\"");

WriteAttribute("aria-valuenow", Tuple.Create(" aria-valuenow=\"", 1031), Tuple.Create("\"", 1065)
            
            #line 31 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 1047), Tuple.Create<System.Object, System.Int32>(item.TotalAnswers
            
            #line default
            #line hidden
, 1047), false)
);

WriteLiteral(" aria-valuemin=\"0\"");

WriteAttribute("aria-valuemax", Tuple.Create(" aria-valuemax=\"", 1084), Tuple.Create("\"", 1116)
            
            #line 31 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 1100), Tuple.Create<System.Object, System.Int32>(item.MaxAnswers
            
            #line default
            #line hidden
, 1100), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 1117), Tuple.Create("\"", 1164)
, Tuple.Create(Tuple.Create("", 1125), Tuple.Create("width:", 1125), true)
            
            #line 31 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                                                                , Tuple.Create(Tuple.Create(" ", 1131), Tuple.Create<System.Object, System.Int32>(answerPercentage
            
            #line default
            #line hidden
, 1132), false)
, Tuple.Create(Tuple.Create("", 1149), Tuple.Create("%;", 1149), true)
, Tuple.Create(Tuple.Create(" ", 1151), Tuple.Create("min-width:", 1152), true)
, Tuple.Create(Tuple.Create(" ", 1162), Tuple.Create("0", 1163), true)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                     Write(item.TotalAnswers);

            
            #line default
            #line hidden
WriteLiteral(" out of ");

            
            #line 32 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                                               Write(item.MaxAnswers);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><small>");

            
            #line 35 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                       Write(string.Format(@"( {0} / {1} )", item.TotalAnswers, item.MaxAnswers));

            
            #line default
            #line hidden
WriteLiteral("</small></div>\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 38 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(Html.DisplayFor(modelItem => item.CategoryName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 41 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(Html.ActionLink("View", "Details", new { questionId = item.QuestionId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 44 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>");

        }
    }
}
#pragma warning restore 1591
