#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    
    #line 1 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
    using Dilemma.Web.Extensions;
    
    #line default
    #line hidden
    using Disposable.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/QuestionListViewModel.cshtml")]
    public partial class QuestionListViewModel_ : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.QuestionListViewModel>
    {
        public QuestionListViewModel_()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
  
    Func<bool, bool, bool, string> stateClass = (approved, rejected, ismine) =>
    {
        if (approved)
        {
            if (ismine)
            {
                return "bg-info";
            }

            return "bg-success";
        }

        if (rejected)
        {
            return "bg-danger";
        }

        // queued or other
        return "bg-warning";
    };

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>Question</th>\r\n        <th");

WriteLiteral(" style=\"min-width: 110px\"");

WriteLiteral(">Created</th>\r\n        <th");

WriteLiteral(" style=\"min-width: 110px\"");

WriteLiteral(">Closes</th>\r\n        <th>Answers</th>\r\n        <th>Category</th>\r\n        <th>Ap" +
"proved</th>\r\n        <th>Rejected</th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 39 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
 foreach (var item in Model.Questions)
{
    var answerPercentage = Convert.ToInt32(item.TotalAnswers * 100 / item.MaxAnswers);
    

            
            #line default
            #line hidden
WriteLiteral("    <tr");

WriteAttribute("class", Tuple.Create(" class=\"", 951), Tuple.Create("\"", 1023)
            
            #line 43 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 959), Tuple.Create<System.Object, System.Int32>(stateClass(item.IsApproved, item.IsRejected, item.IsMyQuestion)
            
            #line default
            #line hidden
, 959), false)
);

WriteLiteral(">\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(Html.DisplayFor(modelItem => item.Text));

            
            #line default
            #line hidden
WriteLiteral(" \r\n        </td>\r\n        <td>\r\n            <div");

WriteAttribute("title", Tuple.Create(" title=\"", 1141), Tuple.Create("\"", 1170)
            
            #line 48 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 1149), Tuple.Create<System.Object, System.Int32>(item.CreatedDateTime
            
            #line default
            #line hidden
, 1149), false)
);

WriteLiteral(">");

            
            #line 48 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                          Write(item.CreatedDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </td>\r\n        <td>\r\n            <div");

WriteAttribute("title", Tuple.Create(" title=\"", 1263), Tuple.Create("\"", 1291)
            
            #line 51 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 1271), Tuple.Create<System.Object, System.Int32>(item.ClosesDateTime
            
            #line default
            #line hidden
, 1271), false)
);

WriteLiteral(">");

            
            #line 51 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                         Write(item.ClosesDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </td>\r\n        <td>\r\n            <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(" style=\"margin-bottom: 5px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"progress-bar\"");

WriteLiteral(" role=\"progressbar\"");

WriteAttribute("aria-valuenow", Tuple.Create(" aria-valuenow=\"", 1490), Tuple.Create("\"", 1524)
            
            #line 55 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 1506), Tuple.Create<System.Object, System.Int32>(item.TotalAnswers
            
            #line default
            #line hidden
, 1506), false)
);

WriteLiteral(" aria-valuemin=\"0\"");

WriteAttribute("aria-valuemax", Tuple.Create(" aria-valuemax=\"", 1543), Tuple.Create("\"", 1575)
            
            #line 55 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 1559), Tuple.Create<System.Object, System.Int32>(item.MaxAnswers
            
            #line default
            #line hidden
, 1559), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 1576), Tuple.Create("\"", 1623)
, Tuple.Create(Tuple.Create("", 1584), Tuple.Create("width:", 1584), true)
            
            #line 55 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                                                                , Tuple.Create(Tuple.Create(" ", 1590), Tuple.Create<System.Object, System.Int32>(answerPercentage
            
            #line default
            #line hidden
, 1591), false)
, Tuple.Create(Tuple.Create("", 1608), Tuple.Create("%;", 1608), true)
, Tuple.Create(Tuple.Create(" ", 1610), Tuple.Create("min-width:", 1611), true)
, Tuple.Create(Tuple.Create(" ", 1621), Tuple.Create("0", 1622), true)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                     Write(item.TotalAnswers);

            
            #line default
            #line hidden
WriteLiteral(" out of ");

            
            #line 56 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                                               Write(item.MaxAnswers);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><small>");

            
            #line 59 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
                                       Write(string.Format(@"( {0} / {1} )", item.TotalAnswers, item.MaxAnswers));

            
            #line default
            #line hidden
WriteLiteral("</small></div>\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 62 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(Html.DisplayFor(modelItem => item.CategoryName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 65 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(item.IsApproved);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 68 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(item.IsRejected);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 71 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
       Write(Html.ActionLink("View", "Details", new { questionId = item.QuestionId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 74 "..\..\Views\Shared\DisplayTemplates\QuestionListViewModel.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>");

        }
    }
}
#pragma warning restore 1591
