#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Sidebar.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Sidebar_cshtml_ : System.Web.Mvc.WebViewPage<Dilemma.Web.ViewModels.SidebarViewModel>
    {
        public _Views_Shared_DisplayTemplates_Sidebar_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
  
    var showNotifications = ViewBag.HideNotifications == null || !ViewBag.HideNotifications;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"Card Card--sidebar-ask\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"Card-section\"");

WriteLiteral(">\r\n        <h2");

WriteLiteral(" class=\"pv10 h2 align-center\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span>\r\n            Ask\r\n        </h2>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"Card-section\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"h4 info pt10 pb20 align-center\"");

WriteLiteral(">What\'s on your mind?</h3>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 477), Tuple.Create("\"", 511)
            
            #line 18 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 484), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Ask")
            
            #line default
            #line hidden
, 484), false)
);

WriteLiteral(" class=\"Button--ask\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span>\r\n            Share Your Dilemma\r\n        </a>\r\n    </div>\r\n</div>\r\n     " +
"   \r\n<div");

WriteLiteral(" class=\"Card Card--sidebar-profile\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 704), Tuple.Create("\"", 784)
, Tuple.Create(Tuple.Create("", 712), Tuple.Create("Card-section", 712), true)
, Tuple.Create(Tuple.Create(" ", 724), Tuple.Create("Rank", 725), true)
, Tuple.Create(Tuple.Create(" ", 729), Tuple.Create("user-is-level-", 730), true)
            
            #line 26 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 744), Tuple.Create<System.Object, System.Int32>(Model.UserStatsViewModel.UserRank.Level
            
            #line default
            #line hidden
, 744), false)
);

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"Rank-image\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" data-icon=\"user-level\"");

WriteLiteral("></span>\r\n            <div");

WriteLiteral(" class=\"Rank-text\"");

WriteLiteral(">\r\n                Your rank: ");

            
            #line 31 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                      Write(Model.UserStatsViewModel.UserRank.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div><!-- Rank-image -->\r\n\r\n        <div");

WriteLiteral(" class=\"Rank-ometer-container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Rank-ometer\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Rank-ometer-amount\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1167), Tuple.Create("\"", 1227)
, Tuple.Create(Tuple.Create("", 1175), Tuple.Create("width:", 1175), true)
            
            #line 37 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 1181), Tuple.Create<System.Object, System.Int32>(Model.UserStatsViewModel.UserRank.Percentage
            
            #line default
            #line hidden
, 1181), false)
, Tuple.Create(Tuple.Create("", 1226), Tuple.Create("%", 1226), true)
);

WriteLiteral("></div>\r\n            </div> \r\n            <div");

WriteLiteral(" class=\"Image-ometer \"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/Content/images/wise-ometer.png\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Image-ometer-amount\"");

WriteLiteral("></div>\r\n            </div>               \r\n        </div>\r\n\r\n    </div>\r\n\r\n    <" +
"div");

WriteLiteral(" class=\"Rank-table\"");

WriteLiteral(">\r\n        <table>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 50 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatsViewModel.TotalQuestions);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Dilemmas posed</th>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 54 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatsViewModel.TotalAnswers);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Answers given</th>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 58 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatsViewModel.TotalStarVotes);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Best answers</th>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 62 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatsViewModel.TotalPopularVotes);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Up-votes</th>\r\n            </tr>\r\n        </table> \r\n    </div>  <!-- Rank -->  " +
"       \r\n");

            
            #line 67 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
    
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
     if (showNotifications)
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"Card-section Card-section--notification Card-go--container\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2423), Tuple.Create("\"", 2461)
            
            #line 69 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
    , Tuple.Create(Tuple.Create("", 2430), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Profile")
            
            #line default
            #line hidden
, 2430), false)
);

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"Card-go--trigger\"");

WriteLiteral("></span>\r\n            <div");

WriteLiteral(" style=\"width: 60px; overflow: hidden; float: left;\"");

WriteLiteral(">\r\n                <!-- <div class=\"disc-label right\">99</div> -->\r\n             " +
"   <div");

WriteLiteral(" class=\"disc-label right\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"notification\"");

WriteLiteral("></span>\r\n                </div>\r\n            </div>\r\n            <div>\r\n        " +
"        <div");

WriteLiteral(" class=\"Card-label--small\"");

WriteLiteral(">You have ");

            
            #line 78 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                                   Write(Model.Notifications.Count());

            
            #line default
            #line hidden
WriteLiteral(" new</div>\r\n                <div>\r\n                    Notifications             " +
" \r\n                </div>\r\n            </div>\r\n        </a>\r\n");

            
            #line 84 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"featured-content\"");

WriteLiteral(">\r\n    <img");

WriteLiteral(" src=\"/Content/images/ads/300x250_uap.gif\"");

WriteLiteral(" width=\"300\"");

WriteLiteral(" height=\"250\"");

WriteLiteral(" >\r\n</div>\r\n\r\n");

            
            #line 91 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
 if (showNotifications)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 94 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
   Write(Html.DisplayForList(x => x.Notifications, "Notifications"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 96 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
