#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Sidebar.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Sidebar_cshtml_ : System.Web.Mvc.WebViewPage<Dilemma.Web.ViewModels.SidebarViewModel>
    {
        public _Views_Shared_DisplayTemplates_Sidebar_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
  
    var showNotifications = ViewBag.HideNotifications == null || !ViewBag.HideNotifications;

    var notificationCount = Model.Notifications.Count();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"Card Card--sidebar-ask\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"Card-section\"");

WriteLiteral(">\r\n        <h2");

WriteLiteral(" class=\"pv10 h2 align-center\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span>\r\n            Ask\r\n        </h2>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"Card-section\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"h4 info pt10 pb20 align-center\"");

WriteLiteral(">What\'s on your mind?</h3>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 566), Tuple.Create("\"", 644)
            
            #line 21 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 573), Tuple.Create<System.Object, System.Int32>(Url.ActionWithCategory("Index", "Ask", (string)ViewBag.Category, true)
            
            #line default
            #line hidden
, 573), false)
);

WriteLiteral(" class=\"Button--ask\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span>\r\n            Share Your Dilemma\r\n        </a>\r\n    </div>\r\n</div>\r\n     " +
"   \r\n<div");

WriteLiteral(" class=\"Card Card--sidebar-profile\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 837), Tuple.Create("\"", 918)
, Tuple.Create(Tuple.Create("", 845), Tuple.Create("Card-section", 845), true)
, Tuple.Create(Tuple.Create(" ", 857), Tuple.Create("Rank", 858), true)
, Tuple.Create(Tuple.Create(" ", 862), Tuple.Create("user-is-level-", 863), true)
            
            #line 29 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 877), Tuple.Create<System.Object, System.Int32>(Model.UserStatistics.UserRank.Rank.Level
            
            #line default
            #line hidden
, 877), false)
);

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"Rank-image\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" data-icon=\"user-level\"");

WriteLiteral("></span>\r\n            <div");

WriteLiteral(" class=\"Rank-text\"");

WriteLiteral(">\r\n                Your rank: ");

            
            #line 34 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                      Write(Model.UserStatistics.UserRank.Rank.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div><!-- Rank-image -->\r\n\r\n        <div");

WriteLiteral(" class=\"Rank-ometer-container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Rank-ometer\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Rank-ometer-amount\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1302), Tuple.Create("\"", 1358)
, Tuple.Create(Tuple.Create("", 1310), Tuple.Create("width:", 1310), true)
            
            #line 40 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 1316), Tuple.Create<System.Object, System.Int32>(Model.UserStatistics.UserRank.Percentage
            
            #line default
            #line hidden
, 1316), false)
, Tuple.Create(Tuple.Create("", 1357), Tuple.Create("%", 1357), true)
);

WriteLiteral("></div>\r\n            </div> \r\n            <div");

WriteLiteral(" class=\"Image-ometer \"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/Content/images/wise-ometer.png\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Image-ometer-amount\"");

WriteLiteral("></div>\r\n            </div>               \r\n        </div>\r\n\r\n    </div>\r\n\r\n    <" +
"div");

WriteLiteral(" class=\"Rank-table\"");

WriteLiteral(">\r\n        <table>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 53 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatistics.TotalQuestions);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Dilemmas posed</th>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatistics.TotalAnswers);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Answers given</th>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatistics.TotalStarVotes);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Best answers</th>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"Rank-score\"");

WriteLiteral(">");

            
            #line 65 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
                                  Write(Model.UserStatistics.TotalPopularVotes);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <th");

WriteLiteral(" class=\"Rank-facet\"");

WriteLiteral(">Up-votes</th>\r\n            </tr>\r\n        </table> \r\n    </div>  <!-- Rank -->  " +
"       \r\n");

            
            #line 70 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
     if (showNotifications)
    {
        if (notificationCount > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"Card-section Card-section--notification Card-go--container\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2589), Tuple.Create("\"", 2627)
            
            #line 74 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
        , Tuple.Create(Tuple.Create("", 2596), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Profile")
            
            #line default
            #line hidden
, 2596), false)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"Card-go--trigger\"");

WriteLiteral("></span>\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
           Write(Html.DisplayFor(x => x.Notifications, "SidebarNotificationSummary"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </a>\r\n");

            
            #line 78 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"Card-section Card-section--notification\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 82 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
           Write(Html.DisplayFor(x => x.Notifications, "SidebarNotificationSummary"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 84 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"featured-content\"");

WriteLiteral(">\r\n    <img");

WriteLiteral(" src=\"/Content/images/ads/300x250_uap.gif\"");

WriteLiteral(" width=\"300\"");

WriteLiteral(" height=\"250\"");

WriteLiteral(" >\r\n</div>\r\n\r\n");

            
            #line 92 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
 if (showNotifications)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 95 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
   Write(Html.DisplayForList(x => x.Notifications, "Notifications"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 97 "..\..\Views\Shared\DisplayTemplates\Sidebar.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
