#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\SidebarNotificationSummary.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/SidebarNotificationSummary.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_SidebarNotificationSummary_cshtml_ : System.Web.Mvc.WebViewPage<IEnumerable<Dilemma.Business.ViewModels.NotificationListViewModel>>
    {
        public _Views_Shared_DisplayTemplates_SidebarNotificationSummary_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\SidebarNotificationSummary.cshtml"
  
    var notificationCount = Model.Count();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" style=\"width: 60px; overflow: hidden; float: left;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"disc-label right\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" data-icon=\"notification\"");

WriteLiteral("></span>\r\n    </div>\r\n</div>\r\n<div>\r\n    <div");

WriteLiteral(" class=\"Card-label--small\"");

WriteLiteral(">You have ");

            
            #line 15 "..\..\Views\Shared\DisplayTemplates\SidebarNotificationSummary.cshtml"
                                        Write(notificationCount == 0 ? "no" : notificationCount.ToString(CultureInfo.CurrentCulture));

            
            #line default
            #line hidden
WriteLiteral(" new</div>\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\SidebarNotificationSummary.cshtml"
    Write(notificationCount == 1 ? "Notification" : "Notifications");

            
            #line default
            #line hidden
WriteLiteral("          \r\n    </div>\r\n</div>\r\n \r\n");

        }
    }
}
#pragma warning restore 1591
