#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Offline/Index.cshtml")]
    public partial class _Views_Offline_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Offline_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Offline\Index.cshtml"
  
    ViewBag.Title = "Offline";
    ViewBag.Offline = true;

            
            #line default
            #line hidden
WriteLiteral(@"

<h2>Looks like we've got a Dilemma of our own!</h2>

<p>We're taking a little maintenance break while we update our code to bring you an even better place to Ask, Advise and Vote.</p>

<p>Feel free to hit refesh like a maniac - we'll be back online shortly.</p>
");

        }
    }
}
#pragma warning restore 1591
