#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Notification
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Disposable.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Notification/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<Dilemma.Business.ViewModels.NotificationListViewModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Notification\Index.cshtml"
  
    ViewBag.Title = "Notifications";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Notifications</h2>\r\n\r\n");

            
            #line 9 "..\..\Views\Notification\Index.cshtml"
 foreach (var viewModel in Model)
{
    var rowClass = viewModel.IsActioned ? string.Empty : "bg-info";
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"col-md-12\"");

WriteAttribute("href", Tuple.Create(" href=\"", 314), Tuple.Create("\"", 480)
            
            #line 14 "..\..\Views\Notification\Index.cshtml"
, Tuple.Create(Tuple.Create("", 321), Tuple.Create<System.Object, System.Int32>(Url.Action(viewModel.NotificationRoute.Action, viewModel.NotificationRoute.Controller, new RouteValueDictionary(viewModel.GetRouteData()), Request.Url.Scheme)
            
            #line default
            #line hidden
, 321), false)
);

WriteLiteral(">\r\n            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 500), Tuple.Create("\"", 517)
            
            #line 15 "..\..\Views\Notification\Index.cshtml"
, Tuple.Create(Tuple.Create("", 508), Tuple.Create<System.Object, System.Int32>(rowClass
            
            #line default
            #line hidden
, 508), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\Notification\Index.cshtml"
           Write(viewModel.GetMessage());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </a>\r\n    </div>\r\n");

            
            #line 20 "..\..\Views\Notification\Index.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
