#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Disposable.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/Answer.cshtml")]
    public partial class Answer : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.QuestionDetailsViewModel>
    {
        public Answer()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Question\Answer.cshtml"
  
    ViewBag.Title = "Details";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 7 "..\..\Views\Question\Answer.cshtml"
Write(Html.DisplayFor(x => x.QuestionViewModel));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\Question\Answer.cshtml"
 if (Model.Answer != null)
{
    using (Html.BeginForm("Answer", "Question", new { questionId = Model.QuestionViewModel.QuestionId, answerId = Model.Answer.AnswerId }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
         
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Question\Answer.cshtml"
    Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Question\Answer.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Question\Answer.cshtml"
       Write(Html.LabelFor(x => x.Answer.Text, new { @class = "col-md-2 col-sm-3 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10 col-sm-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\Question\Answer.cshtml"
           Write(Html.TextAreaFor(x => x.Answer.Text, new { @class = "form-control", rows="10"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Question\Answer.cshtml"
           Write(Html.ValidationMessageFor(x => x.Answer.Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 22 "..\..\Views\Question\Answer.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n");

            
            #line 28 "..\..\Views\Question\Answer.cshtml"
    }
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row top-buffer-xlg\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-8 col-md-offset-2\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"bg-danger padded\"");

WriteLiteral(">No more answers allowed...</p>\r\n        </div>\r\n    </div>\r\n");

            
            #line 37 "..\..\Views\Question\Answer.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
