#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Web;
    using Disposable.Web.TwitterBootstrap3.MVC5;
    using TwitterBootstrap3;
    
    #line 1 "..\..\Views\Question\Create.cshtml"
    using TwitterBootstrapMVC;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/Create.cshtml")]
    public partial class Create : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.QuestionViewModel>
    {
        public Create()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Question\Create.cshtml"
  
    ViewBag.Title = "Ask a question";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Views\Question\Create.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 9 "..\..\Views\Question\Create.cshtml"
 using (var f = Html.Bootstrap().Begin(new Form("Create", "Question")))
{
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Question\Create.cshtml"
Write(f.FormGroup().TextAreaFor(m => m.Text).Rows(10).NoLabel());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Question\Create.cshtml"
                                                              ;
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Question\Create.cshtml"
Write(f.FormGroup().CustomControls(Html.Bootstrap().SubmitButton()));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Question\Create.cshtml"
                                                                  
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Question\Create.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
