#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    
    #line 1 "..\..\Views\Question\Details.cshtml"
    using Dilemma.Web.Extensions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Question\Details.cshtml"
    using Microsoft.Ajax.Utilities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Question\Details.cshtml"
    using WebGrease.Css.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.QuestionDetailsViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Question\Details.cshtml"
  
    ViewBag.Title = "Details";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Views\Question\Details.cshtml"
Write(Html.DisplayFor(x => x.QuestionViewModel));

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n");

            
            #line 12 "..\..\Views\Question\Details.cshtml"
 if (Model.CanAnswer)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row top-buffer-xlg\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-8 col-md-offset-2\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Question\Details.cshtml"
       Write(Html.ActionLink("Add an answer", "AnswerSlot", new { questionId = Model.QuestionViewModel.QuestionId }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 19 "..\..\Views\Question\Details.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
