#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.QuestionViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Question\Details.cshtml"
  
    ViewBag.Title = "Details";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Details for ");

            
            #line 7 "..\..\Views\Question\Details.cshtml"
           Write(Model.QuestionId);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
