#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    
    #line 1 "..\..\Views\Question\List.cshtml"
    using Dilemma.Web.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/List.cshtml")]
    public partial class List : System.Web.Mvc.WebViewPage<IEnumerable<Dilemma.Business.ViewModels.QuestionViewModel>>
    {
        public List()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Question\List.cshtml"
  
    ViewBag.Title = "List";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>List</h2>\r\n\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>Question</th>\r\n        <th");

WriteLiteral(" style=\"min-width: 110px\"");

WriteLiteral(">Created</th>\r\n        <th");

WriteLiteral(" style=\"min-width: 110px\"");

WriteLiteral(">Closes</th>\r\n        <th>Answers</th>\r\n        <th>Category</th>\r\n        <th></" +
"th>\r\n    </tr>\r\n\r\n");

            
            #line 20 "..\..\Views\Question\List.cshtml"
 foreach (var item in Model)
{
    var answerPercentage = Convert.ToInt32(item.AnswerCount * 100 / item.MaxAnswers);
    

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 26 "..\..\Views\Question\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Text));

            
            #line default
            #line hidden
WriteLiteral(" \r\n        </td>\r\n        <td>\r\n            <div");

WriteAttribute("title", Tuple.Create(" title=\"", 651), Tuple.Create("\"", 680)
            
            #line 29 "..\..\Views\Question\List.cshtml"
, Tuple.Create(Tuple.Create("", 659), Tuple.Create<System.Object, System.Int32>(item.CreatedDateTime
            
            #line default
            #line hidden
, 659), false)
);

WriteLiteral(">");

            
            #line 29 "..\..\Views\Question\List.cshtml"
                                          Write(item.CreatedDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </td>\r\n        <td>\r\n            <div");

WriteAttribute("title", Tuple.Create(" title=\"", 773), Tuple.Create("\"", 801)
            
            #line 32 "..\..\Views\Question\List.cshtml"
, Tuple.Create(Tuple.Create("", 781), Tuple.Create<System.Object, System.Int32>(item.ClosesDateTime
            
            #line default
            #line hidden
, 781), false)
);

WriteLiteral(">");

            
            #line 32 "..\..\Views\Question\List.cshtml"
                                         Write(item.ClosesDateTime.ToRelativeText());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </td>\r\n        <td>\r\n            <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(" style=\"margin-bottom: 5px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"progress-bar\"");

WriteLiteral(" role=\"progressbar\"");

WriteAttribute("aria-valuenow", Tuple.Create(" aria-valuenow=\"", 1000), Tuple.Create("\"", 1033)
            
            #line 36 "..\..\Views\Question\List.cshtml"
, Tuple.Create(Tuple.Create("", 1016), Tuple.Create<System.Object, System.Int32>(item.AnswerCount
            
            #line default
            #line hidden
, 1016), false)
);

WriteLiteral(" aria-valuemin=\"0\"");

WriteAttribute("aria-valuemax", Tuple.Create(" aria-valuemax=\"", 1052), Tuple.Create("\"", 1084)
            
            #line 36 "..\..\Views\Question\List.cshtml"
                                                , Tuple.Create(Tuple.Create("", 1068), Tuple.Create<System.Object, System.Int32>(item.MaxAnswers
            
            #line default
            #line hidden
, 1068), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 1085), Tuple.Create("\"", 1132)
, Tuple.Create(Tuple.Create("", 1093), Tuple.Create("width:", 1093), true)
            
            #line 36 "..\..\Views\Question\List.cshtml"
                                                                               , Tuple.Create(Tuple.Create(" ", 1099), Tuple.Create<System.Object, System.Int32>(answerPercentage
            
            #line default
            #line hidden
, 1100), false)
, Tuple.Create(Tuple.Create("", 1117), Tuple.Create("%;", 1117), true)
, Tuple.Create(Tuple.Create(" ", 1119), Tuple.Create("min-width:", 1120), true)
, Tuple.Create(Tuple.Create(" ", 1130), Tuple.Create("0", 1131), true)
);

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 37 "..\..\Views\Question\List.cshtml"
                                     Write(item.AnswerCount);

            
            #line default
            #line hidden
WriteLiteral(" out of ");

            
            #line 37 "..\..\Views\Question\List.cshtml"
                                                              Write(item.MaxAnswers);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><small>");

            
            #line 40 "..\..\Views\Question\List.cshtml"
                                       Write(string.Format(@"( {0} / {1} )", item.AnswerCount, item.MaxAnswers));

            
            #line default
            #line hidden
WriteLiteral("</small></div>\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Views\Question\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.CategoryName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Views\Question\List.cshtml"
       Write(Html.ActionLink("View", "Details", new { id=item.QuestionId }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");

WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 52 "..\..\Views\Question\List.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
