#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Disposable.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/Seeder.cshtml")]
    public partial class Seeder : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.CreateQuestionViewModel>
    {
        public Seeder()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Question\Seeder.cshtml"
  
    ViewBag.Title = "Help us start dilemma";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Views\Question\Seeder.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 8 "..\..\Views\Question\Seeder.cshtml"
 if (ViewBag.ShowConfirmation == true)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"line\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" style=\"margin-top: 20px;\"");

WriteLiteral(">Thanks for your help!</div>\r\n    </div>\r\n");

            
            #line 13 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" style=\"margin-top: 40px;\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Question\Seeder.cshtml"
       Write(Html.ActionLink("I've got something else to ask!", "Create", "Question", new { @class="btn btn-success btn-large left", style="font-weight: bold"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 19 "..\..\Views\Question\Seeder.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"line\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">Our objective is to populate the site with as many dilemmas as possible for laun" +
"ch.</div>\r\n    </div>\r\n");

            
            #line 25 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"line\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">We have set this up so there is no means of us knowing who is posting what quest" +
"ion as they go against system generated dummy users.</div>\r\n    </div>\r\n");

            
            #line 29 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <p>&nbsp;</p>\r\n");

            
            #line 31 "..\..\Views\Question\Seeder.cshtml"
    
    using (Html.BeginForm("Seeder", "Question", FormMethod.Post, new { @class = "", role = "form" }))
    {
        
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Question\Seeder.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Question\Seeder.cshtml"
                                
    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 37 "..\..\Views\Question\Seeder.cshtml"
       Write(Html.Label("What’s on your mind?", new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Views\Question\Seeder.cshtml"
           Write(Html.TextAreaFor(x => x.Text, new { @class = "form-control", rows="10"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Views\Question\Seeder.cshtml"
           Write(Html.ValidationMessageFor(x => x.Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 43 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Views\Question\Seeder.cshtml"
           Write(Html.Label("Which category should your dilemma be placed in?", new { @class = "" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 48 "..\..\Views\Question\Seeder.cshtml"
               Write(Html.DropDownListFor(x => x.CategoryId, new SelectList(Model.Categories, "CategoryId", "Name"), string.Empty, new { @class = "form-control", style="min-width: 400px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Views\Question\Seeder.cshtml"
               Write(Html.ValidationMessageFor(x => x.CategoryId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 53 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"line\"");

WriteLiteral(" style=\"margin-top: 20px;\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-large left\"");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(" value=\"Add My Dilemma\"");

WriteLiteral(" />\r\n        </div>\r\n");

            
            #line 57 "..\..\Views\Question\Seeder.cshtml"
    }
}

            
            #line default
            #line hidden
DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 60 "..\..\Views\Question\Seeder.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
