#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Disposable.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/Seeder.cshtml")]
    public partial class Seeder : System.Web.Mvc.WebViewPage<Dilemma.Business.ViewModels.CreateQuestionViewModel>
    {
        public Seeder()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Question\Seeder.cshtml"
  
    ViewBag.Title = "Help us start dilemma";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Views\Question\Seeder.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 8 "..\..\Views\Question\Seeder.cshtml"
 if (ViewBag.ShowConfirmation == true)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>Thanks for your help!</div>\r\n");

WriteLiteral("    <div>Please create text for this page.</div>\r\n");

            
            #line 12 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Question\Seeder.cshtml"
       Write(Html.ActionLink("I've got something else to ask!", "Create", "Question", new { @class="btn btn-default"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 18 "..\..\Views\Question\Seeder.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">A description of what we\'re doing - emphasise that we can\'t tell who has posted " +
"which question - a new user is created everytime that someone visits this page s" +
"o we can\'t even tell if someone asks two questions.</div>\r\n    </div>\r\n");

            
            #line 24 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <p>&nbsp;</p>\r\n");

            
            #line 26 "..\..\Views\Question\Seeder.cshtml"
    
    using (Html.BeginForm("Seeder", "Question", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Question\Seeder.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Question\Seeder.cshtml"
                                
    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Question\Seeder.cshtml"
       Write(Html.LabelFor(x => x.Text, new { @class = "col-md-2 col-sm-3 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10 col-sm-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 34 "..\..\Views\Question\Seeder.cshtml"
           Write(Html.TextAreaFor(x => x.Text, new { @class = "form-control", rows="10"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Views\Question\Seeder.cshtml"
           Write(Html.ValidationMessageFor(x => x.Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 38 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 40 "..\..\Views\Question\Seeder.cshtml"
       Write(Html.LabelFor(x => x.CategoryId, new { @class = "col-md-2 col-sm-3 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-3 col-sm-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Views\Question\Seeder.cshtml"
           Write(Html.DropDownListFor(x => x.CategoryId, new SelectList(Model.Categories, "CategoryId", "Name"), string.Empty, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 43 "..\..\Views\Question\Seeder.cshtml"
           Write(Html.ValidationMessageFor(x => x.CategoryId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 46 "..\..\Views\Question\Seeder.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n");

            
            #line 52 "..\..\Views\Question\Seeder.cshtml"
    }
}

            
            #line default
            #line hidden
DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 55 "..\..\Views\Question\Seeder.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
