#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<Dilemma.Web.ViewModels.DilemmasViewModel>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"layout-home\"");

WriteLiteral(">\r\n\r\n    <section");

WriteLiteral(" class=\"section-style-1\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"hero-wrap\"");

WriteLiteral(">\r\n            <img");

WriteLiteral(" src=\"/Content/images/hero.jpg\"");

WriteLiteral(" width=\"1080\"");

WriteLiteral(" height=\"390\"");

WriteLiteral(" class=\"hero\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n        </div>\r\n      \r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <h1><img");

WriteLiteral(" class=\"brand-logo\"");

WriteLiteral(" src=\"/Content/images/logo.png\"");

WriteLiteral(" width=\"600\"");

WriteLiteral(" alt=\"\"");

WriteLiteral("></h1>\r\n            <h2>\r\n                <span");

WriteLiteral(" class=\"animated anim-message-1  brand-1-of-3\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span> \r\n                    <a");

WriteLiteral(" href=\"#ask\"");

WriteLiteral(" class=\"disguise-link\"");

WriteLiteral(">Ask</a>\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"animated anim-message-2 brand-1-of-3\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"advise\"");

WriteLiteral("></span>\r\n                    <a");

WriteLiteral(" href=\"#advise\"");

WriteLiteral(" class=\"disguise-link\"");

WriteLiteral(">Advise</a>\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"animated anim-message-3 brand-1-of-3\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"vote\"");

WriteLiteral("></span> \r\n                    <a");

WriteLiteral(" href=\"#vote\"");

WriteLiteral(" class=\"disguise-link\"");

WriteLiteral(">Vote</a>\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"animated anim-message-4\"");

WriteLiteral(">\r\n                    In Complete Anonymity        \r\n                </span>\r\n  " +
"          </h2>\r\n\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1262), Tuple.Create("\"", 1301)
            
            #line 33 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1269), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dilemmas")
            
            #line default
            #line hidden
, 1269), false)
);

WriteLiteral(" class=\"Button Button--red mv25 animated anim-tada\"");

WriteLiteral(">Get Started</a>\r\n            <p>\r\n                <a");

WriteLiteral(" href=\"#more-info\"");

WriteLiteral(" class=\"scroll-down-for-more\"");

WriteLiteral(">\r\n                    Or scroll down to learn more\r\n                    <br><spa" +
"n");

WriteLiteral(" data-icon=\"down-circle\"");

WriteLiteral(" style=\"font-size: 90px;margin-top: 30px;\"");

WriteLiteral("></span>\r\n                </a>\r\n            </p>        \r\n        </div><!-- .wra" +
"p -->\r\n    </section>\r\n\r\n    <section");

WriteLiteral(" id=\"more-info\"");

WriteLiteral(" class=\"section-style-2\"");

WriteLiteral(">  \r\n      \r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <img");

WriteLiteral(" src=\"/Content/images/icon-large.png\"");

WriteLiteral(" width=\"140\"");

WriteLiteral(" height=\"140\"");

WriteLiteral(" class=\"ma20\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"h1\"");

WriteLiteral(">What is Our Dilemmas?</h2>\r\n            <p");

WriteLiteral(" class=\"text-large\"");

WriteLiteral(">OUR DILEMMAS is a safe online space to ask personal or difficult questions in co" +
"mplete anonymity</p>\r\n            <ul");

WriteLiteral(" class=\"unstyled inline h4\"");

WriteLiteral(">\r\n                <li><a");

WriteLiteral(" href=\"#anonymity\"");

WriteLiteral(">Anonymity</a></li>\r\n                <li><a");

WriteLiteral(" href=\"#ask\"");

WriteLiteral(">Ask</a></li>\r\n                <li><a");

WriteLiteral(" href=\"#advise\"");

WriteLiteral(">Advise</a></li>\r\n                <li><a");

WriteLiteral(" href=\"#vote\"");

WriteLiteral(">Vote</a></li>\r\n            </ul>        \r\n        </div><!-- .wrap -->\r\n    </se" +
"ction>\r\n    \r\n    <section");

WriteLiteral(" class=\"section-style-3\"");

WriteLiteral(" id=\"anonymity\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">        \r\n            <div");

WriteLiteral(" class=\"Media Media-to-stack\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Media-img\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"user-2\"");

WriteLiteral(" class=\"dilemmicon-massive\"");

WriteLiteral("></span>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"Media-text\"");

WriteLiteral(@">
                    <h2>Anonymity</h2>
                    <p>Questions and Answers disappear in 15 days</p>  
                    <p>Your account is completely anonymous. None of your details are stored on our servers. Your account is stored in an encrypted cookie on your phone or PC, which you can easily remove by deleting your cookies.</p>
                </div>
            </div><!-- Media Media-to-stack -->
        </div><!-- .wrap -->
    </section>

    <section");

WriteLiteral(" class=\"section-style-4\"");

WriteLiteral(" id=\"ask\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Media Media-to-stack\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Media-img\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral(" class=\"dilemmicon-massive\"");

WriteLiteral("></span>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"Media-text\"");

WriteLiteral(@">
                    <h2>Ask</h2>
                    <p>Don’t struggle alone — share your dilemma.</p><p>Get advice, and learn from the experience of others.</p>  
                    <p>Dilemmas are divided into 6 categories: Personal, Family, Relationships, Work, Sex and Teenage. </p>            
                </div>
            </div><!-- Media Media-to-stack -->
        
     
        </div><!-- .wrap -->
    </section>


    <section");

WriteLiteral(" class=\"section-style-5\"");

WriteLiteral(" id=\"advise\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Media Media-to-stack\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Media-img\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"advise\"");

WriteLiteral(" class=\"dilemmicon-massive\"");

WriteLiteral("></span>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"Media-text\"");

WriteLiteral(@">
                    <h2>Advise</h2>
                    <p>You’ve been there? Give questioners the benefit of your knowledge and experience. </p>
                    <p>Get reputation points when people vote your answers up. Can you attain the rank of guru?</p>             
                </div>
            </div><!-- Media Media-to-stack -->
        </div><!-- .wrap -->
    </section>

    <section");

WriteLiteral(" class=\"section-style-6\"");

WriteLiteral(" id=\"vote\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Media Media-to-stack\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"Media-img\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" data-icon=\"vote\"");

WriteLiteral(" class=\"dilemmicon-massive\"");

WriteLiteral("></span>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"Media-text\"");

WriteLiteral(@">
                    <h2>Vote</h2>
                    <p>Whose advice is the best? What would you do in that situation?</p>
                    <p>Browse through dilemmas and vote for the best answers.</p>     
                    <p>More votes = more points for you.</p>               
                </div>
            </div><!-- Media Media-to-stack -->
        

        </div><!-- .wrap -->
    </section>

    <section");

WriteLiteral(" class=\"section-style-7\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <h2>Ask * Advise * Vote</h2>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5550), Tuple.Create("\"", 5589)
            
            #line 127 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5557), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dilemmas")
            
            #line default
            #line hidden
, 5557), false)
);

WriteLiteral(" class=\"Button Button--red\"");

WriteLiteral(">Get Started</a>        \r\n        </div><!-- .wrap -->\r\n    </section>\r\n\r\n</div>\r" +
"\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        document.getElementsByTagName(\'body\')[0].className+=\' page-home\';\r\n   " +
" </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
