#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilemma.Web.Views.Prelaunch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Disposable.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Prelaunch/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Dilemma.Web.Controllers.PrelaunchViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Prelaunch\Index.cshtml"
  
    ViewBag.Title = "Get in early!";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Views\Prelaunch\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 8 "..\..\Views\Prelaunch\Index.cshtml"
 using (Html.BeginForm("Create", "Question", FormMethod.Post, new { role = "form" }))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Prelaunch\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Prelaunch\Index.cshtml"
                            
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Prelaunch\Index.cshtml"
   Write(Html.Label("What's your question?", new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Prelaunch\Index.cshtml"
       Write(Html.TextAreaFor(x => x.Question, new { @class = "form-control", rows="10"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 18 "..\..\Views\Prelaunch\Index.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n");

            
            #line 24 "..\..\Views\Prelaunch\Index.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
