#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Answers\Index.cshtml"
    using Dilemma.Business.ViewModels;
    
    #line default
    #line hidden
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Answers/Index.cshtml")]
    public partial class _Views_Answers_Index_cshtml : System.Web.Mvc.WebViewPage<Dilemma.Web.ViewModels.DilemmaDetailsViewModel>
    {
        public _Views_Answers_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Answers\Index.cshtml"
  
    ViewBag.IsDilemmaViewPage = true;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <h1");

WriteLiteral(" class=\"section-label js-sticky\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"js-sticky--offset\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" data-icon=\"advise\"");

WriteLiteral("></span>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Views\Answers\Index.cshtml"
        Write(Model.QuestionDetails.CanAnswer ? "Answer this dilemma" : "Check out this dilemma");

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n    </h1>\r\n\r\n<div");

WriteLiteral(" class=\"line\"");

WriteLiteral(">\r\n\r\n    <aside");

WriteLiteral(" class=\"sidebar\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Answers\Index.cshtml"
   Write(Html.DisplayFor(x => x.Sidebar, "Sidebar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </aside>\r\n\r\n    <main");

WriteLiteral(" role=\"main\"");

WriteLiteral(" class=\"main\"");

WriteLiteral(">\r\n    \r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Views\Answers\Index.cshtml"
   Write(Html.DisplayFor(x => x.QuestionDetails.QuestionViewModel, "QuestionSummary"));

            
            #line default
            #line hidden
WriteLiteral("\r\n          \r\n");

            
            #line 25 "..\..\Views\Answers\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Answers\Index.cshtml"
         if (Model.QuestionDetails.CanAnswer)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"js-answer-container\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Views\Answers\Index.cshtml"
           Write(Html.Partial("EditorTemplates/Advise", new AnswerViewModel()));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 30 "..\..\Views\Answers\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        \r\n");

            
            #line 32 "..\..\Views\Answers\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Answers\Index.cshtml"
         if (Model.QuestionDetails.CanFollowup)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"js-followup-container\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Views\Answers\Index.cshtml"
           Write(Html.Partial("EditorTemplates/Followup", new FollowupViewModel()));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 37 "..\..\Views\Answers\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        \r\n");

            
            #line 39 "..\..\Views\Answers\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Answers\Index.cshtml"
         if (Model.QuestionDetails.QuestionViewModel.HasFollowup)
        {
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Answers\Index.cshtml"
       Write(Html.DisplayFor(x => x.QuestionDetails.QuestionViewModel.Followup, "FollowupResponse"));

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Answers\Index.cshtml"
                                                                                                   
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 44 "..\..\Views\Answers\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Answers\Index.cshtml"
         foreach (var answer in Model.QuestionDetails.QuestionViewModel.Answers)
        {
            
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Answers\Index.cshtml"
       Write(Html.DisplayFor(x => answer, "Answer", new { Model.QuestionDetails.CanVote, Model.QuestionDetails.QuestionViewModel.IsMyQuestion }));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Answers\Index.cshtml"
                                                                                                                                                
        }

            
            #line default
            #line hidden
WriteLiteral("        \r\n    </main><!-- main-->   \r\n\r\n</div>\r\n\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    \r\n    <script>\r\n        window.resetAnswerHook = function() {\r\n            " +
"$(\'#js-button-answer\').click(function(e) {\r\n                e.preventDefault();\r" +
"\n                $.ajax({\r\n                    type: \"POST\",\r\n                  " +
"  url: \'");

            
            #line 62 "..\..\Views\Answers\Index.cshtml"
                     Write(Url.Action("Advise", "Ajax"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    dataType: ""html"",
                    data: $('form.Answer--window').serialize(),
                    success: function(result) {
                        $(""#js-answer-container"").html(result);
                        window.resetAnswerHook();
                    },
                    error: function() {
                    }
                });
            });
        };

        $(document).ready(window.resetAnswerHook);
    </script>
    
    <script>
        window.resetFollowupHook = function () {
            $('#js-button-followup').click(function (e) {
                e.preventDefault();
                $.ajax({
                    type: ""POST"",
                    url: '");

            
            #line 84 "..\..\Views\Answers\Index.cshtml"
                     Write(Url.Action("Followup", "Ajax"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    dataType: ""html"",
                    data: $('form.Answer--window').serialize(),
                    success: function (result) {
                        $(""#js-followup-container"").html(result);
                        window.resetFollowupHook();
                    },
                    error: function () {
                    }
                });
            });
        };

        $(document).ready(window.resetFollowupHook);
    </script>
    
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        document.getElementsByTagName(\'body\')[0].className+=\' page-answer\';\r\n " +
"   </script>\r\n\r\n");

});

        }
    }
}
#pragma warning restore 1591
