#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral("/>\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n\r\n    <title>\r\n");

            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
         if (string.IsNullOrEmpty(ViewBag.Title))
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("OurDilemmas");

WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("OurDilemmas - ");

WriteLiteral(" ");

            
            #line 16 "..\..\Views\Shared\_Layout.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\_Layout.cshtml"
                                   Write(ViewBag.Title);

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\_Layout.cshtml"
                                                      ;
        }

            
            #line default
            #line hidden
WriteLiteral("    </title>\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n    <!--icons-->\r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" href=\"/Content/images/icons/favicon.png\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon-precomposed\"");

WriteLiteral(" href=\"/Content/images/icons/apple-touch-icon-precomposed.png\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral("/>\r\n\r\n    <!-- send jquery to the foot of the page -->\r\n    <script");

WriteLiteral(" type=\'text/javascript\'");

WriteLiteral(">window.q = []; window.$ = function (f) { q.push(f) }</script>\r\n\r\n</head>\r\n<body>" +
"\r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("Header"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n");

WriteLiteral("    ");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("Modals"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n    <div");

WriteLiteral(" class=\"page-bd\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 37 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    \r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("Footer"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n");

WriteLiteral("    ");

            
            #line 43 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 44 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/cookiedirective"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 46 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/homegrown"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n    \r\n");

WriteLiteral("    ");

            
            #line 49 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">$.each(q, function (i, f) { $(f); })</script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
