#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Footer.cshtml")]
    public partial class _Views_Shared_Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Footer_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<footer");

WriteLiteral(" role=\"contentinfo\"");

WriteLiteral(" class=\"page-ft\"");

WriteLiteral(">\r\n    <small>\r\n        <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"unstyled inline with-separators\"");

WriteLiteral(">\r\n                <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Privacy Policy</a></li>\r\n                <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Terms &amp; Conditions</a></li>\r\n                <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Cookies Policy</a></li>\r\n                <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Contact Us</a></li>\r\n            </ul>\r\n            <div");

WriteLiteral(" class=\"copyright\"");

WriteLiteral(">&copy;&#160;Our Dilemmas&#160;");

            
            #line 11 "..\..\Views\Shared\Footer.cshtml"
                                                            Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral("-100&#160;All&#160;rights&#160;reserved</div>\r\n        </div><!-- wrap-->\r\n    </" +
"small>\r\n</footer>\r\n");

        }
    }
}
#pragma warning restore 1591
