#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\Shared\Header.cshtml"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Header.cshtml"
    using Dilemma.Business.ViewModels;
    
    #line default
    #line hidden
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Header.cshtml")]
    public partial class _Views_Shared_Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Header_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Header.cshtml"
  
    var tidyRegex = new Regex("[^a-zA-Z]");
    Func<string, string> tidyString = (x) => tidyRegex.Replace(x, string.Empty).ToLower();
    var counter = 3;
    Func<int> getNextCounter = () => counter++;
    Func<string, string> getMenuClass = (x) => x == tidyString(ViewBag.Category ?? string.Empty) ? " is-page-current " : string.Empty;
    
    var isOffline = ViewBag.Offline == true;

    var unreadNotifications = 99;

    var dilemmasPath = Url.Action("Index", "Dilemmas");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<header");

WriteLiteral(" role=\"banner\"");

WriteLiteral(" class=\"page-hd\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-default navbar-inverse\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 814), Tuple.Create("\"", 853)
            
            #line 24 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 821), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dilemmas")
            
            #line default
            #line hidden
, 821), false)
);

WriteLiteral(" rel=\"home\"");

WriteLiteral(" class=\"page-logo\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/Content/images/device.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"60\"");

WriteLiteral(" style=\"position: absolute;top: -5px; margin-right: 5px;\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/Content/images/logo.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"200\"");

WriteLiteral(" style=\" margin: 10px 0 0 70px;\"");

WriteLiteral(">\r\n                    </a>\r\n                </div>\r\n");

            
            #line 29 "..\..\Views\Shared\Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\Header.cshtml"
                 if (!isOffline)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <ul");

WriteLiteral(" class=\"nav navbar-nav right\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"dropdown nav-level-1\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1385), Tuple.Create("\"", 1405)
            
            #line 33 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 1392), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 1392), false)
);

WriteLiteral(" class=\"dropdown-toggle nav-level-1-link js-nav-level-2-menu-trigger\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"advise\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">\r\n                                    Advise &amp; Vote \r\n                      " +
"              <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n                                </span>\r\n                \r\n            " +
"                </a>\r\n                            <ul");

WriteLiteral(" class=\"nav-level-2-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n                                <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1965), Tuple.Create("\"", 2037)
, Tuple.Create(Tuple.Create("", 1973), Tuple.Create("nav-level-2", 1973), true)
, Tuple.Create(Tuple.Create(" ", 1984), Tuple.Create("in-category-1", 1985), true)
, Tuple.Create(Tuple.Create(" ", 1998), Tuple.Create("js-categories-all", 1999), true)
            
            #line 42 "..\..\Views\Shared\Header.cshtml"
      , Tuple.Create(Tuple.Create(" ", 2016), Tuple.Create<System.Object, System.Int32>(getMenuClass("all")
            
            #line default
            #line hidden
, 2017), false)
);

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2079), Tuple.Create("\"", 2099)
            
            #line 43 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 2086), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 2086), false)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                                        All Categories\r\n               " +
"                     </a>\r\n                                </li>\r\n              " +
"                  <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2410), Tuple.Create("\"", 2494)
, Tuple.Create(Tuple.Create("", 2418), Tuple.Create("nav-level-2", 2418), true)
, Tuple.Create(Tuple.Create(" ", 2429), Tuple.Create("in-category-2", 2430), true)
, Tuple.Create(Tuple.Create(" ", 2443), Tuple.Create("js-categories-bookmarks", 2444), true)
            
            #line 48 "..\..\Views\Shared\Header.cshtml"
            , Tuple.Create(Tuple.Create(" ", 2467), Tuple.Create<System.Object, System.Int32>(getMenuClass("bookmarks")
            
            #line default
            #line hidden
, 2468), false)
);

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2536), Tuple.Create("\"", 2566)
            
            #line 49 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 2543), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 2543), false)
, Tuple.Create(Tuple.Create("", 2556), Tuple.Create("/bookmarks", 2556), true)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                                        My Bookmarks\r\n                 " +
"                   </a>\r\n                                </li>\r\n");

            
            #line 54 "..\..\Views\Shared\Header.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Shared\Header.cshtml"
                                 foreach (CategoryViewModel category in ViewBag.Categories)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 3007), Tuple.Create("\"", 3097)
, Tuple.Create(Tuple.Create("", 3015), Tuple.Create("nav-level-2", 3015), true)
, Tuple.Create(Tuple.Create(" ", 3026), Tuple.Create("in-category-", 3027), true)
            
            #line 56 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3039), Tuple.Create<System.Object, System.Int32>(getNextCounter()
            
            #line default
            #line hidden
, 3039), false)
            
            #line 56 "..\..\Views\Shared\Header.cshtml"
        , Tuple.Create(Tuple.Create(" ", 3056), Tuple.Create<System.Object, System.Int32>(getMenuClass(tidyString(category.Name))
            
            #line default
            #line hidden
, 3057), false)
);

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3143), Tuple.Create("\"", 3190)
            
            #line 57 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3150), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 3150), false)
, Tuple.Create(Tuple.Create("", 3163), Tuple.Create("/", 3163), true)
            
            #line 57 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3164), Tuple.Create<System.Object, System.Int32>(tidyString(category.Name)
            
            #line default
            #line hidden
, 3164), false)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n");

WriteLiteral("                                            ");

            
            #line 59 "..\..\Views\Shared\Header.cshtml"
                                       Write(category.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </a>\r\n                                 " +
"   </li>\r\n");

            
            #line 62 "..\..\Views\Shared\Header.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </li>\r\n               " +
"         <li");

WriteLiteral(" class=\"nav-level-1\"");

WriteLiteral(">\r\n                            <!-- <a href=\"#\" data-toggle=\"modal\" data-target=\"" +
"#modal-ask\"> -->\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3759), Tuple.Create("\"", 3793)
            
            #line 67 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3766), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Ask")
            
            #line default
            #line hidden
, 3766), false)
);

WriteLiteral(" class=\"nav-level-1-link\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">Ask</span>\r\n                            </a>\r\n                        </li>\r\n   " +
"                     <li");

WriteLiteral(" class=\"nav-level-1\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4105), Tuple.Create("\"", 4143)
            
            #line 73 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 4112), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Profile")
            
            #line default
            #line hidden
, 4112), false)
);

WriteLiteral(" class=\"nav-level-1-link\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"user\"");

WriteLiteral("></span>\r\n");

            
            #line 75 "..\..\Views\Shared\Header.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Shared\Header.cshtml"
                                 if (unreadNotifications > 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <span");

WriteLiteral(" class=\"nav-unread-notifications\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 78 "..\..\Views\Shared\Header.cshtml"
                                   Write(unreadNotifications);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </span>\r\n");

            
            #line 80 "..\..\Views\Shared\Header.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">Profile</span>\r\n                            </a>\r\n                        </li>\r" +
"\n                    </ul>\r\n");

            
            #line 85 "..\..\Views\Shared\Header.cshtml"
                }         

            
            #line default
            #line hidden
WriteLiteral("            </div><!-- wrap -->\r\n        </div>\r\n    </nav>\r\n\r\n</header>\r\n<!-- ba" +
"nner-->\r\n");

        }
    }
}
#pragma warning restore 1591
