#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\Shared\Header.cshtml"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Header.cshtml"
    using Dilemma.Business.ViewModels;
    
    #line default
    #line hidden
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Header.cshtml")]
    public partial class _Views_Shared_Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Header_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Header.cshtml"
  
    var tidyRegex = new Regex("[^a-zA-Z]");
    Func<string, string> tidyString = (x) => tidyRegex.Replace(x, string.Empty).ToLower();
    var counter = 3;
    Func<int> getNextCounter = () => counter++;
    Func<string, string> getMenuClass = (x) => x == tidyString(ViewBag.Category ?? string.Empty) ? " is-page-current " : string.Empty;
    
    var isOffline = ViewBag.Offline == true;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<header");

WriteLiteral(" role=\"banner\"");

WriteLiteral(" class=\"page-hd\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-default navbar-inverse\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 718), Tuple.Create("\"", 757)
            
            #line 20 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 725), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dilemmas")
            
            #line default
            #line hidden
, 725), false)
);

WriteLiteral(" rel=\"home\"");

WriteLiteral(" class=\"page-logo\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/Content/images/device.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"60\"");

WriteLiteral(" style=\"position: absolute;top: -5px; margin-right: 5px;\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/Content/images/logo.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"200\"");

WriteLiteral(" style=\" margin: 10px 0 0 70px;\"");

WriteLiteral(">\r\n                    </a>\r\n                </div>\r\n");

            
            #line 25 "..\..\Views\Shared\Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\Header.cshtml"
                 if (!isOffline)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <ul");

WriteLiteral(" class=\"nav navbar-nav right\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"dropdown nav-level-1\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"javascript://click\"");

WriteLiteral(" class=\"dropdown-toggle nav-level-1-link js-nav-level-2-menu-trigger\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"advise\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">\r\n                                    Advise &amp; Vote \r\n                      " +
"              <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n                                </span>\r\n                \r\n            " +
"                </a>\r\n                            <ul");

WriteLiteral(" class=\"nav-level-2-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n                                <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1874), Tuple.Create("\"", 1946)
, Tuple.Create(Tuple.Create("", 1882), Tuple.Create("nav-level-2", 1882), true)
, Tuple.Create(Tuple.Create(" ", 1893), Tuple.Create("in-category-1", 1894), true)
, Tuple.Create(Tuple.Create(" ", 1907), Tuple.Create("js-categories-all", 1908), true)
            
            #line 38 "..\..\Views\Shared\Header.cshtml"
      , Tuple.Create(Tuple.Create(" ", 1925), Tuple.Create<System.Object, System.Int32>(getMenuClass("all")
            
            #line default
            #line hidden
, 1926), false)
);

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1988), Tuple.Create("\"", 2027)
            
            #line 39 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 1995), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dilemmas")
            
            #line default
            #line hidden
, 1995), false)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                                        All Categories\r\n               " +
"                     </a>\r\n                                </li>\r\n              " +
"                  <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2338), Tuple.Create("\"", 2422)
, Tuple.Create(Tuple.Create("", 2346), Tuple.Create("nav-level-2", 2346), true)
, Tuple.Create(Tuple.Create(" ", 2357), Tuple.Create("in-category-2", 2358), true)
, Tuple.Create(Tuple.Create(" ", 2371), Tuple.Create("js-categories-bookmarks", 2372), true)
            
            #line 44 "..\..\Views\Shared\Header.cshtml"
            , Tuple.Create(Tuple.Create(" ", 2395), Tuple.Create<System.Object, System.Int32>(getMenuClass("bookmarks")
            
            #line default
            #line hidden
, 2396), false)
);

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2464), Tuple.Create("\"", 2528)
            
            #line 45 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 2471), Tuple.Create<System.Object, System.Int32>(Url.ActionWithCategory("Index", "Dilemmas", "bookmarks")
            
            #line default
            #line hidden
, 2471), false)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                                        My Bookmarks\r\n                 " +
"                   </a>\r\n                                </li>\r\n");

            
            #line 50 "..\..\Views\Shared\Header.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\Header.cshtml"
                                 foreach (CategoryViewModel category in ViewBag.Categories)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2969), Tuple.Create("\"", 3059)
, Tuple.Create(Tuple.Create("", 2977), Tuple.Create("nav-level-2", 2977), true)
, Tuple.Create(Tuple.Create(" ", 2988), Tuple.Create("in-category-", 2989), true)
            
            #line 52 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3001), Tuple.Create<System.Object, System.Int32>(getNextCounter()
            
            #line default
            #line hidden
, 3001), false)
            
            #line 52 "..\..\Views\Shared\Header.cshtml"
        , Tuple.Create(Tuple.Create(" ", 3018), Tuple.Create<System.Object, System.Int32>(getMenuClass(tidyString(category.Name))
            
            #line default
            #line hidden
, 3019), false)
);

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3105), Tuple.Create("\"", 3183)
            
            #line 53 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3112), Tuple.Create<System.Object, System.Int32>(Url.ActionWithCategory("Index", "Dilemmas", tidyString(category.Name))
            
            #line default
            #line hidden
, 3112), false)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n");

WriteLiteral("                                            ");

            
            #line 55 "..\..\Views\Shared\Header.cshtml"
                                       Write(category.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </a>\r\n                                 " +
"   </li>\r\n");

            
            #line 58 "..\..\Views\Shared\Header.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </li>\r\n               " +
"         <li");

WriteLiteral(" class=\"nav-level-1\"");

WriteLiteral(">\r\n                            <!-- <a href=\"#\" data-toggle=\"modal\" data-target=\"" +
"#modal-ask\"> -->\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3752), Tuple.Create("\"", 3830)
            
            #line 63 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3759), Tuple.Create<System.Object, System.Int32>(Url.ActionWithCategory("Index", "Ask", (string)ViewBag.Category, true)
            
            #line default
            #line hidden
, 3759), false)
);

WriteLiteral(" class=\"nav-level-1-link\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">Ask</span>\r\n                            </a>\r\n                        </li>\r\n   " +
"                     <li");

WriteLiteral(" class=\"nav-level-1\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4142), Tuple.Create("\"", 4180)
            
            #line 69 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 4149), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Profile")
            
            #line default
            #line hidden
, 4149), false)
);

WriteLiteral(" class=\"nav-level-1-link\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"user\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">Profile</span>\r\n                            </a>\r\n                        </li>\r" +
"\n                    </ul>\r\n");

            
            #line 75 "..\..\Views\Shared\Header.cshtml"
                }         

            
            #line default
            #line hidden
WriteLiteral("            </div><!-- wrap -->\r\n        </div>\r\n    </nav>\r\n\r\n</header>\r\n<!-- ba" +
"nner-->\r\n");

        }
    }
}
#pragma warning restore 1591
