#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\Shared\Header.cshtml"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Header.cshtml"
    using Dilemma.Business.ViewModels;
    
    #line default
    #line hidden
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Header.cshtml")]
    public partial class _Views_Shared_Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Header_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Header.cshtml"
  
    var tidyRegex = new Regex("[^a-zA-Z]");
    Func<string, string> tidyString = (x) => tidyRegex.Replace(x, string.Empty).ToLower();
    var counter = 3;
    Func<int> getNextCounter = () => counter++;
    Func<string, string> getMenuClass = (x) => x == tidyString(ViewBag.Category ?? string.Empty) ? " is-page-current " : string.Empty;
    
    var isOffline = ViewBag.Offline == true;

    var dilemmasPath = Url.Action("Index", "Dilemmas");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<header");

WriteLiteral(" role=\"banner\"");

WriteLiteral(" class=\"page-hd\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-default navbar-inverse\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"wrap\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 777), Tuple.Create("\"", 816)
            
            #line 22 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 784), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dilemmas")
            
            #line default
            #line hidden
, 784), false)
);

WriteLiteral(" rel=\"home\"");

WriteLiteral(" class=\"page-logo\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/Content/images/device.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"60\"");

WriteLiteral(" style=\"position: absolute;top: -5px; margin-right: 5px;\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/Content/images/logo.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" width=\"200\"");

WriteLiteral(" style=\" margin: 10px 0 0 70px;\"");

WriteLiteral(">\r\n                    </a>\r\n                </div>\r\n");

            
            #line 27 "..\..\Views\Shared\Header.cshtml"
                
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Shared\Header.cshtml"
                 if (!isOffline)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <ul");

WriteLiteral(" class=\"nav navbar-nav right\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"dropdown nav-level-1\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1348), Tuple.Create("\"", 1368)
            
            #line 31 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 1355), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 1355), false)
);

WriteLiteral(" class=\"dropdown-toggle nav-level-1-link js-nav-level-2-menu-trigger\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"advise\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">\r\n                                    Advise &amp; Vote \r\n                      " +
"              <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n                                </span>\r\n                \r\n            " +
"                </a>\r\n                            <ul");

WriteLiteral(" class=\"nav-level-2-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n                                <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1928), Tuple.Create("\"", 2000)
, Tuple.Create(Tuple.Create("", 1936), Tuple.Create("nav-level-2", 1936), true)
, Tuple.Create(Tuple.Create(" ", 1947), Tuple.Create("in-category-1", 1948), true)
, Tuple.Create(Tuple.Create(" ", 1961), Tuple.Create("js-categories-all", 1962), true)
            
            #line 40 "..\..\Views\Shared\Header.cshtml"
      , Tuple.Create(Tuple.Create(" ", 1979), Tuple.Create<System.Object, System.Int32>(getMenuClass("all")
            
            #line default
            #line hidden
, 1980), false)
);

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2042), Tuple.Create("\"", 2062)
            
            #line 41 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 2049), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 2049), false)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                                        All Categories\r\n               " +
"                     </a>\r\n                                </li>\r\n              " +
"                  <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2373), Tuple.Create("\"", 2457)
, Tuple.Create(Tuple.Create("", 2381), Tuple.Create("nav-level-2", 2381), true)
, Tuple.Create(Tuple.Create(" ", 2392), Tuple.Create("in-category-2", 2393), true)
, Tuple.Create(Tuple.Create(" ", 2406), Tuple.Create("js-categories-bookmarks", 2407), true)
            
            #line 46 "..\..\Views\Shared\Header.cshtml"
            , Tuple.Create(Tuple.Create(" ", 2430), Tuple.Create<System.Object, System.Int32>(getMenuClass("bookmarks")
            
            #line default
            #line hidden
, 2431), false)
);

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2499), Tuple.Create("\"", 2529)
            
            #line 47 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 2506), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 2506), false)
, Tuple.Create(Tuple.Create("", 2519), Tuple.Create("/bookmarks", 2519), true)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                                        My Bookmarks\r\n                 " +
"                   </a>\r\n                                </li>\r\n");

            
            #line 52 "..\..\Views\Shared\Header.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\Header.cshtml"
                                 foreach (CategoryViewModel category in ViewBag.Categories)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2970), Tuple.Create("\"", 3060)
, Tuple.Create(Tuple.Create("", 2978), Tuple.Create("nav-level-2", 2978), true)
, Tuple.Create(Tuple.Create(" ", 2989), Tuple.Create("in-category-", 2990), true)
            
            #line 54 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3002), Tuple.Create<System.Object, System.Int32>(getNextCounter()
            
            #line default
            #line hidden
, 3002), false)
            
            #line 54 "..\..\Views\Shared\Header.cshtml"
        , Tuple.Create(Tuple.Create(" ", 3019), Tuple.Create<System.Object, System.Int32>(getMenuClass(tidyString(category.Name))
            
            #line default
            #line hidden
, 3020), false)
);

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3106), Tuple.Create("\"", 3153)
            
            #line 55 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3113), Tuple.Create<System.Object, System.Int32>(dilemmasPath
            
            #line default
            #line hidden
, 3113), false)
, Tuple.Create(Tuple.Create("", 3126), Tuple.Create("/", 3126), true)
            
            #line 55 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3127), Tuple.Create<System.Object, System.Int32>(tidyString(category.Name)
            
            #line default
            #line hidden
, 3127), false)
);

WriteLiteral(" class=\"nav-level-2-link\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n");

WriteLiteral("                                            ");

            
            #line 57 "..\..\Views\Shared\Header.cshtml"
                                       Write(category.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </a>\r\n                                 " +
"   </li>\r\n");

            
            #line 60 "..\..\Views\Shared\Header.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </li>\r\n               " +
"         <li");

WriteLiteral(" class=\"nav-level-1\"");

WriteLiteral(">\r\n                            <!-- <a href=\"#\" data-toggle=\"modal\" data-target=\"" +
"#modal-ask\"> -->\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3722), Tuple.Create("\"", 3756)
            
            #line 65 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 3729), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Ask")
            
            #line default
            #line hidden
, 3729), false)
);

WriteLiteral(" class=\"nav-level-1-link\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"ask\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">Ask</span>\r\n                            </a>\r\n                        </li>\r\n   " +
"                     <li");

WriteLiteral(" class=\"nav-level-1\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4068), Tuple.Create("\"", 4106)
            
            #line 71 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 4075), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Profile")
            
            #line default
            #line hidden
, 4075), false)
);

WriteLiteral(" class=\"nav-level-1-link\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" data-icon=\"user\"");

WriteLiteral("></span>\r\n                                <span");

WriteLiteral(" class=\"nav-level-1-text\"");

WriteLiteral(">Profile</span>\r\n                            </a>\r\n                        </li>\r" +
"\n                    </ul>\r\n");

            
            #line 77 "..\..\Views\Shared\Header.cshtml"
                }         

            
            #line default
            #line hidden
WriteLiteral("            </div><!-- wrap -->\r\n        </div>\r\n    </nav>\r\n\r\n</header>\r\n<!-- ba" +
"nner-->\r\n");

        }
    }
}
#pragma warning restore 1591
