#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dilemma.Common;
    using Dilemma.Web;
    using Dilemma.Web.Extensions;
    using Disposable.Common.Extensions;
    using Disposable.Web.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Modals.cshtml")]
    public partial class _Views_Shared_Modals_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Modals_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!-- Modal -->\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modal-flag\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" action=\"\"");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <legend>Why are you you reporting this?</legend>\r\n        " +
"            <div");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                        <label>\r\n                            <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"flag_reason\"");

WriteLiteral(" id=\"flag_reason_1\"");

WriteLiteral(" value=\"option1\"");

WriteLiteral(">\r\n                            Offensive or abusive content\r\n                    " +
"    </label>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                        <label>\r\n                            <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"flag_reason\"");

WriteLiteral(" id=\"flag_reason_2\"");

WriteLiteral(" value=\"option2\"");

WriteLiteral(">\r\n                            Spam / unsolicited advertising\r\n                  " +
"      </label>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                        <label>\r\n                            <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"flag_reason\"");

WriteLiteral(" id=\"flag_reason_3\"");

WriteLiteral(" value=\"option3\"");

WriteLiteral(">\r\n                            Not an answer or unrelated to this dilemma\r\n      " +
"                  </label>\r\n                    </div>\r\n                </div><!" +
"-- form-group -->\r\n            </div><!-- modal-body -->\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"line\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn Button Button-danger btn-large left js-flag-confirm\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" >\r\n                        <span");

WriteLiteral(" data-icon=\"flag-active\"");

WriteLiteral("></span>\r\n                        <strong>Report<span");

WriteLiteral(" class=\"size-s-and-up inline\"");

WriteLiteral("> this</span> post</strong>\r\n                    </button>\r\n                    <" +
"button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"Button right\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                        Close\r\n                    </button>           " +
"   \r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n    </form>\r\n" +
"</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
